from datetime import datetime


def generate_report(N, P, K, temperature, humidity, ph, rainfall, crop):
    """
    Generate a text report for the recommended crop.
    """

    report = f"""
====================================================
        CROP RECOMMENDATION REPORT
====================================================

Date : {datetime.now().strftime("%d-%m-%Y %H:%M")}

---------------- Soil Information ----------------

Nitrogen (N)     : {N}
Phosphorus (P)   : {P}
Potassium (K)    : {K}
Temperature      : {temperature} °C
Humidity         : {humidity} %
pH               : {ph}
Rainfall         : {rainfall} mm

--------------------------------------------------

Recommended Crop : {crop.upper()}

--------------------------------------------------

Generated by:

🌾 Intelligent Crop Recommendation AI Agent
Machine Learning Model : Random Forest

==================================================
"""

    return report